#Probar inicio de sesión POST

POST http://127.0.0.1:5000/login
Content-Type: application/x-www-form-urlencoded

username=Daynna&password=Nala2014


POST http://127.0.0.1:5000/login
Content-Type: application/x-www-form-urlencoded

username=Javier&password=Vale1546
